---
title: "Project Hub"
author: "Frankie"
# date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  rmarkdown::html_document:
    includes:
      before_body: header.html
      after_body: footer.html
    toc: false
    # toc_depth: 2
    theme: cosmo
    css: style.css
---

***************************************

<!-- <main> -->

<!-- ## This site -->

<!-- This is a project hub that hosts my computing projects and classworks, which span physics, computer science and finance. Links below redirect to the GitHub repos. -->

<!-- *************************************** -->

## Projects

### Finance

| Topic | Work |
| ----- | ----------- |
| Option Pricing (C++) | Developed an object-oriented option pricing library with an extendable facade design pattern that<br>(1) supports efficient valuation of vanilla & exotic contracts with early-exercise/path-dependence/basket feature and Greeks calculation via bi/trinomial tree, numerical integration, Fourier inverse, PDE schemes and Monte Carlo simulation, accommodating various stock price and stochastic vol processes, such as: jump-diffusion, Heston, Levy, regime-switching<br>(2) offers robust backtest engines for realistic simulation of dynamic delta/gamma/theta-neutral option hedging strategies riding on market-calibrated underlying price dynamics and modellable/interpolated vol surface accounting for transaction cost<br>(3) streamlines market data to compute and construct implied vol surface with live tabulation as well as visualize Greeks vs strike price curves on an interactive Python dashboard using Dash and Plotly package<br>(4) provides access to live market quotes by wrappers around broker API to identify opportunities with proprietary vol arbitrage-based trading signals on at-the-money options to speculate on mispriced implied vol by a dynamic delta-hedged position |
| Technical Trading Simulation (R) | • Implemented a buy-and-hold trading strategy on Hong Kong blue-chips with trading decision informed by technical indicator $\mu/\sigma^2$ with a threshold optimized over 100 stocks, estimating the drift $\mu$ from moving average with a volatility-based dynamic window and the instantaneous vol $\sigma$ from time series models like EWMA and GARCH<br>• Performed historical backtest by calibrating to a 2-year window and then simulating trades over 15 years iterating over 50 blue-chips, quantified the strategy by analyzing return distribution stats, risk-return ratios and risk metrics like VaR and ES |
| Spin Model of Market (C) | • Applied Monte Carlo simulation to model stock price dynamics with the Ising spin model, which consists of discrete-state coupled spins with stochastic flip decisions depending on the mean-field spin, historical states and neighboring spin grids to realistically mimic the stock market with interacting traders psychologically impacted by broad market sentiment<br>• Performed statistical tests on resemblance to real stock prices in terms of non-normality, tail distribution and autocorrelation<br>• Calibrated parameters to generate “stylized facts” of asset like heavy-tailed returns, long memory and volatility clustering<br> |

### Physics

| Topic | Work |
| ----- | ----------- |
| Network Modeling (Python) | • Reconstructed neuron connectivity matrix from electrical signal series of rat cortical neuron cultures by a correlation-based algorithm and a noise-induced covariance method using Python, implemented on computing cloud with efficient vectorization and parallelization, offering a 20x improvement in speed<br>• Compared the matrix reconstruction from the two algorithms using accuracy metrics such as sensitivity and specificity<br>• Explored different dynamical models of network, implemented network models following academia papers and simulated time series variables from the large system of sparse coupled stochastic differential equations representing over 4000 neurons<br>• Analyzed model-generated signal series for numerical spike detection and drew comparison with experimental data in terms of spiking activity and spike distributional statistics to evaluate the performance of different models<br>• Investigated network features causing the long-tailed spike counts through regression and cluster analysis on the large dataset of network parameters including total spike counts, node degrees and average coupling strengths<br>• Proposed a network shuffling technique that allows for marginal manipulation of network features to study the impacts of a network feature on total spike count distribution, and concluded the statistical significance of incoming coupling strength |
| Crystal Geometry Optimization (C) | • Implemented an empirical three-body potential (Tersoff potential) on crystals that captures atomic angular dependences<br>• Optimized crystal geometry of an initially perturbed configuration of atoms by relaxing atomic spacings and positions using steepest gradient and conjugate gradient optimization schemes that were efficiently coded |
| Molecular Simulation (C) | • Simulated the molecular dynamics of an interacting gas under Lennard-Jones potential<br>• Investigated the radial distribution of particles and temperature variation when coupled to a heat bath<br>• Tested the accuracy of numerous iterative schemes (e.g. Euler, Euler-Cromer, Verlet algorithm) by observing how energy is conserved |
| Dynamical Features of Escape Panic (C) | • Simulated escape panic in different environmental settings such as a smoky room and a long corridor with obstacles by a realistic mechanical model of human interaction that incorporates physical and psychological factors<br>• Analyzed escape efficiency and congestion subject to corridor size, shape, pedestrian flow and panic parameters<br>• The model recovers real-world crowd behaviors including jams, incoordination and herding tendency |

<!-- ### Computer Science -->

<!-- | Topic | Work | -->
<!-- | ----- | ----------- | -->
<!-- | Hex game and AI (C++) | • Wrote up an interface for the Hex board game in C++, built upon my graph class and algorithms<br>• Implemented AI game strategies (e.g. Monte Carlo selection of moves, alpha-beta minimax) for human-machine play | -->
<!-- | Graph Algorithms (C++) | • Wrote up a priority queue and graph class in C++<br>• Implemented graph search algorithms, such as Dijkstra's shortest path search and Prim's minimum spanning tree algorithm | -->

<!-- *************************************** -->

<!-- ## Awards -->

<!-- | Award | About | -->
<!-- | ----- | ----------- | -->
<!-- | Dean's Honors List<br>(_CUHK Science Faculty, 2018 & 2019_) |  | -->
<!-- | [InnoTech Scholarship](https://innotechscholarship.hkfyg.org.hk/en/aim-of-the-scholarship/) / HSBC Scholar<br>(_InnoTech Commission & HSBC, 2019_) | (i) Acknowledged my academic achievement in science, devotion to innovation & technology, and passion in making science popular<br>(ii) Sponsored my exchange program to UC Berkeley in Spring 2020<br>[CUHK press release](https://www.cpr.cuhk.edu.hk/en/press_detail.php?id=3015&t=six-cuhk-students-awarded-the-innovation-and-technology-scholarship) [HKEJ report](http://startupbeat.hkej.com/?p=74912) | -->

<!-- *************************************** -->

<!-- ## Certificates -->

<!-- * (_CFA_) Level I Pass -->
<!-- * (_FRM_) Level I Pass -->
<!-- * (_Coursera_) Financial Engineering and Risk Management Part [I](https://www.coursera.org/account/accomplishments/certificate/4QM7VMM6MFA3),[II](https://www.coursera.org/account/accomplishments/certificate/VATN6AHFHQDV) (Columbia University) -->
<!-- * (_Coursera_) [Financial Accounting Fundamentals](https://www.coursera.org/account/accomplishments/certificate/HRYX4A58SDJ3) (University of Virginia) -->
<!-- * (_Coursera_) C++ for C Programmers Part [A](https://www.coursera.org/account/accomplishments/certificate/GE2FSAR58TRZ),[B](https://www.coursera.org/account/accomplishments/certificate/KZUCHSYZDMDM) (UC Santa Cruz) -->

</main>
